version: "3"
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.2.1
    volumes:
      - ./zabbix-server/usr_lib_zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - ./zabbix-server/usr_lib_zabbix/externalscripts:/usr/lib/zabbix/externalscripts
      - ./zabbix-server/var_lib_zabbix/modules:/var/lib/zabbix/modules
      - ./zabbix-server/var_lib_zabbix/enc:/var/lib/zabbix/enc
      - ./zabbix-server/var_lib_zabbix/ssh_keys:/var/lib/zabbix/ssh_keys
      - ./zabbix-server/var_lib_zabbix/ssl/certs:/var/lib/zabbix/ssh/certs
      - ./zabbix-server/var_lib_zabbix/ssl/keys:/var/lib/zabbix/ssh/keys
      - ./zabbix-server/var_lib_zabbix/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca
      - ./zabbix-server/var_lib_zabbix/snmptraps:/var/lib/zabbix/snmptraps
      - ./zabbix-server/var_lib_zabbix/mibs:/var/lib/zabbix/mibs
      - ./zabbix-server/var_lib_zabbix/export:/var/lib/zabbix/export
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=y@min0ma
      - MYSQL_DATABASE=zabbix
      - ZBX_ENABLE_SNMP_TRAPS=true
    depends_on:
      - zabbix-db
    volumes_from:
      - zabbix-snmptraps
    restart: unless-stopped

  zabbix-db:
    image: mariadb:10.5.7
    volumes:
      - ./my/own/datadir:/var/lib/mysql
      - ./my/custom:/etc/mysql/conf.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=y@min0ma
    expose:
      - "3306"
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql
    ports:
      - "80:80"
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=y@min0ma
      - MYSQL_DATABASE=zabbix
      - PHP_TZ=Asia/Tokyo
    depends_on:
      - zabbix-server
      - zabbix-db
      - zabbix-snmptraps
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent
    expose:
      - "10050"
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=Zabbix server
    privileged: true
    depends_on:
      - zabbix-server
    restart: unless-stopped

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps
    ports:
      - "162:162/udp"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=hogehoge
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - zabbix-db
      - zabbix-server
    user: "472"
    restart: unless-stopped

volumes:
  grafana-storage:
    driver: local
