version: "3"
services:
  zabbix-server:
    build: ./zabbix-server
    volumes:
      - ./alertscripts:/usr/lib/zabbix/alertscripts
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=hoge
      - MYSQL_DATABASE=zabbix
    links:
      - zabbix-db
    restart: unless-stopped

  zabbix-db:
    image: mariadb:latest
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hogehoge
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=hoge
    expose:
      - 3306
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-latest
    ports:
      - 80:80
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_SERVER_PORT=10051
      - DB_SERVER_HOST=zabbix-db
      - DB_SERVER_PORT=3306
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=hoge
      - MYSQL_DATABASE=zabbix
      - PHP_TZ=Asia/Tokyo
    links:
      - zabbix-server
      - zabbix-db
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-latest
    expose:
      - 10050
    environment:
      - ZBX_SERVER_HOST=zabbix-server
      - ZBX_HOSTNAME=Zabbix server
    privileged: true
    links:
      - zabbix-server
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=hogehogehoge
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    volumes:
      - ./grafana-storage:/var/lib/grafana
    links:
      - zabbix-db
      - zabbix-server
    user: "472"
    restart: unless-stopped
